name: lotr
services:
    mongo:
        build:
            context: ..
            dockerfile: docker/dockerfile
            target: lotr_mongo
        environment:
            MONGO_INITDB_DATABASE: lotr
        ports:
            - 27017:27017
        restart: on-failure
        volumes:
            - ./db:/data

    backend:
        build: ../backend
        depends_on:
            - mongo
        environment:
            DATABASE_URL: "mongodb://mongo:27017/lotr"
        volumes:
            - ${PWD}/../backend:/backend
        ports:
            - "3001:3001"

    frontend:
        build: ../frontend
        depends_on:
            - mongo
        volumes:
            - ${PWD}/../frontend:/frontend
        ports:
            - "3000:3000"
