name: lotr
services:
    mongo:
        build:
            context: ..
            dockerfile: docker/dockerfile
            target: lotr_mongo
        environment:
            MONGO_INITDB_DATABASE: lotr
        ports:
            - 27017:27017
        restart: on-failure
        volumes:
            - ./db:/data

    backend:
        # Using the debian version rather than alpine to support binary execution e.g. bcrypt
        image: node:21.2
        command: [ "npm", "run", "dev" ]
        depends_on:
            - mongo
        environment:
            DATABASE_URL: "mongodb://mongo:27017/lotr"
        ports:
            - 3001:3001
        volumes:
            - ../backend:/app
        working_dir: /app

    frontend:
        image: node:21.2-alpine
        command: [ "npm", "run", "start" ]
        depends_on:
            - backend
        ports:
            - 3000:3000
        volumes:
            - ../frontend:/app
        working_dir: /app
